###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name":"하얀색 티셔츠",
  "description":"반팔 티셔츠",
  "price":10000,
  "tags":"TSHIRT"
}

###
GET http://localhost:3000/products/234bb1cc-2734-455f-92e3-631adfc23438